// Code generated by protoc-gen-go.
// source: connection.proto
// DO NOT EDIT!

/*
Package connection is a generated protocol buffer package.

It is generated from these files:
	connection.proto

It has these top-level messages:
	ConnectionRequest
	ConnectionResponse
*/
package connection

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ConnectionRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ConnectionRequest) Reset()         { *m = ConnectionRequest{} }
func (m *ConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectionRequest) ProtoMessage()    {}

type ConnectionResponse struct {
	ConnectionId     *uint32 `protobuf:"varint,1,opt,name=connectionId" json:"connectionId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ConnectionResponse) Reset()         { *m = ConnectionResponse{} }
func (m *ConnectionResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectionResponse) ProtoMessage()    {}

func (m *ConnectionResponse) GetConnectionId() uint32 {
	if m != nil && m.ConnectionId != nil {
		return *m.ConnectionId
	}
	return 0
}

func init() {
}
